# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-15 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, db_column='Texto', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('idDiagnostico', models.CharField(db_column='idDiagnostico', max_length=45, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PacienteClinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nss', models.CharField(blank=True, db_column='NSS', max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valorINR', models.DecimalField(db_column='valorINR', decimal_places=10, max_digits=20)),
                ('dosis', models.DecimalField(db_column='dosis', decimal_places=10, max_digits=20)),
                ('duracion', models.CharField(blank=True, db_column='duracion', max_length=45, null=True)),
                ('peso', models.DecimalField(db_column='peso', decimal_places=10, max_digits=20)),
                ('rango', models.CharField(blank=True, db_column='rango', max_length=45, null=True)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INR.Comentario')),
                ('medicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INR.Medicacion')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INR.PacienteClinica')),
            ],
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INR.PacienteClinica'),
        ),
    ]
