# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacienteclinica',
            name='apellido_1',
            field=models.CharField(db_column='apellido_1', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='pacienteclinica',
            name='apellido_2',
            field=models.CharField(db_column='apellido_2', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='pacienteclinica',
            name='ciudad',
            field=models.CharField(db_column='ciudad', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='pacienteclinica',
            name='cp',
            field=models.IntegerField(db_column='cp', null=True),
        ),
        migrations.AddField(
            model_name='pacienteclinica',
            name='dni',
            field=models.CharField(blank=True, db_column='dni', max_length=45),
        ),
        migrations.AddField(
            model_name='pacienteclinica',
            name='fecha_nacimiento',
            field=models.DateField(db_column='fecha_nacimiento', null=True),
        ),
        migrations.AddField(
            model_name='pacienteclinica',
            name='nombre',
            field=models.CharField(db_column='Nombre', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='pacienteclinica',
            name='pais',
            field=models.CharField(db_column='pais', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='pacienteclinica',
            name='password',
            field=models.CharField(db_column='password', default=b'8b9b1258524b49c5ba6646f7f5314ee8', max_length=45),
        ),
        migrations.AddField(
            model_name='pacienteclinica',
            name='provincia',
            field=models.CharField(db_column='provincia', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='pacienteclinica',
            name='sexo',
            field=models.CharField(choices=[('0', 'hombre'), ('1', 'mujer')], default='Sin especificar', max_length=1),
        ),
        migrations.AddField(
            model_name='pacienteclinica',
            name='telefono',
            field=models.IntegerField(db_column='telefono', null=True),
        ),
        migrations.AddField(
            model_name='pacienteclinica',
            name='token',
            field=models.CharField(db_column='token', default=b'e7ca0555a40d4af3b988d37c9b318a3e', max_length=45),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.CharField(blank=True, db_column='NSS', max_length=45, null=True),
        ),
    ]
