# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INR', '0002_auto_20170502_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacienteclinica',
            name='direccion',
            field=models.CharField(db_column='direccion', max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='pacienteclinica',
            name='password',
            field=models.CharField(db_column='password', default=b'8f73138f1de04c4f92fc5669c91e4717', max_length=45),
        ),
        migrations.AlterField(
            model_name='pacienteclinica',
            name='token',
            field=models.CharField(db_column='token', default=b'3d9d0ed7b1664d5ba703889c3bc72022', max_length=45),
        ),
    ]
